export {default as Navbar} from './Navbar/Navbar'
export {default as Heading} from './Heading/Heading'
export {default as Feature} from './Feature/Feature'
export {default as QandA} from './QandA/QandA'
export {default as Cards} from './Cards/Cards'
